### ISSUE TITLE
Settings module: Allow adding of settings tabs and item meta boxes for other plugins

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking-2#3]
- [x] add callback to allow plugins to add tabs/fields in the cb2 settings menu.  
- [x] add callback to allow plugins to add metaboxes for items/locations.

**Comment by flegfleg** [comment]
- [ ] add callback to allow other plugins to add tabs/fields in the cb2 settings menu.  
- [ ] add callback to allow other plugins to add metaboxes for items/locations.

**Comment by flegfleg** [comment]
Example plugin @christianvoigt : [wielebenwir/commons-booking-2-extension-example: Example for extending Commons Booking 2 plugin settings](https://github.com/wielebenwir/commons-booking-2-extension-example) 

Still working on the meta boxes (for post types), and need to fix another bug before i can push the new version.
