### ISSUE TITLE
time formatting enhancements

### ISSUE THREAD

**Issue by hanneskasimir** [wielebenwir/commons-booking-2#596]
- [x] if you book the current day (and it is a full day booking), the date is omitted 

- [x] time formatting booking page

<img width="1069" alt="Bildschirmfoto 2020-03-16 um 14 09 54" src="https://user-images.githubusercontent.com/4009931/76761884-8276d980-6790-11ea-88aa-4e859fcf7393.png">

- [x] time formatting amPM/24h mixup (was:  #585) 
<img width="1069" alt="Bildschirmfoto 2020-03-16 um 14 11 05" src="https://user-images.githubusercontent.com/4009931/76761618-08465500-6790-11ea-9690-c26c92ea60f9.png">

- [x] All day slots not reflected on front end  (was: #437 )

- [x] booking detail: remove date from opening hours (was: #574 ) 

<img width="1069" alt="Bildschirmfoto 2020-03-16 um 14 12 38" src="https://user-images.githubusercontent.com/4009931/76761774-50657780-6790-11ea-936c-397dbcd6a52e.png">

https://miro.com/app/board/o9J_kv8Db5U=/?moveToWidget=3074457347298985780
